"""Tier 3 - validation against NASA CARA's published test cases.

These tests are SKIPPED until fixtures/cara_cases.json is populated.

Per docs/risk-engine-design.md section 6, expected values are transcribed
from CARA's published material, never generated by this implementation.
A fixture file produced by running this code would prove only that the code
agrees with itself. The skip is deliberate and is reported, not hidden.

Fixture schema (one entry per case):

    {
      "case_id":     "<CARA's identifier>",
      "provenance":  "<repo path / paper / table and page>",
      "retrieved":   "<ISO date the value was transcribed>",
      "primary":   {"position_km": [...], "velocity_km_s": [...],
                    "covariance_rtn_m2": [[...],[...],[...]]},
      "secondary": {"position_km": [...], "velocity_km_s": [...],
                    "covariance_rtn_m2": [[...],[...],[...]]},
      "hbr_m":       <float>,
      "expected_pc": <float>,
      "tolerance":   {"rtol": <float>, "justification": "<why this value>"}
    }
"""

import json
import pathlib

import numpy as np
import pytest

from sentinel.risk.engine import assess
from sentinel.risk.types import Conjunction, Method, ObjectState

pytestmark = pytest.mark.tier3

FIXTURES = pathlib.Path(__file__).parent.parent / "fixtures" / "cara_cases.json"


def _load_cases():
    if not FIXTURES.exists():
        return []
    data = json.loads(FIXTURES.read_text())
    return data.get("cases", [])


CASES = _load_cases()


@pytest.mark.skipif(not CASES, reason="CARA fixtures not yet transcribed - see module docstring")
@pytest.mark.parametrize("case", CASES, ids=[c.get("case_id", "?") for c in CASES])
def test_matches_published_cara_case(case):
    def to_state(name, spec):
        return ObjectState(
            object_id=name,
            position_km=np.array(spec["position_km"], dtype=float),
            velocity_km_s=np.array(spec["velocity_km_s"], dtype=float),
            covariance_rtn_m2=np.array(spec["covariance_rtn_m2"], dtype=float),
            radius_m=case["hbr_m"] / 2.0,
        )

    conj = Conjunction(
        primary=to_state("PRIMARY", case["primary"]),
        secondary=to_state("SECONDARY", case["secondary"]),
    )

    result = assess(conj)

    assert result.method is Method.FOSTER_ESTES_2D, result.refusal_reason
    assert np.isclose(result.pc, case["expected_pc"], rtol=case["tolerance"]["rtol"]), (
        f"{case['case_id']}: got {result.pc}, published {case['expected_pc']} "
        f"(provenance: {case['provenance']})"
    )


def test_fixture_file_documents_provenance_for_every_case():
    """A case without provenance is not evidence of anything."""
    for case in CASES:
        assert case.get("provenance"), f"{case.get('case_id')} has no provenance"
        assert case.get("retrieved"), f"{case.get('case_id')} has no retrieval date"
        assert case.get("tolerance", {}).get("justification"), (
            f"{case.get('case_id')} has an unjustified tolerance"
        )
