"""The Compose stack's NATS and Toxiproxy configs (deploy/compose/).

They are rendered from deploy/nats/*.tmpl by the functions the process
harness itself uses (harness/cluster.py), so the leaf permissions (OPSEC,
ADR-009/010) and the four DDIL fixes (docs/system-design.md, "Findings from
the DDIL harness") are the ones every DDIL scenario runs. The only
differences allowed are addresses: a container listens where a process on
one host cannot.
"""

import difflib
import json
import re
import runpy
import shutil
import sys

import pytest

from harness import compose
from harness.cluster import Cluster

ADDRESS_LINE = re.compile(r'^\s*(listen|http|url): "[^"]+"$')


def body(text: str) -> str:
    """A rendered file without its GENERATED header."""
    return "".join(line for line in text.splitlines(keepends=True) if not line.startswith("# GENERATED"))


def committed(name: str) -> str:
    return (compose.COMPOSE_DIR / name).read_text()


def test_the_committed_configs_are_exactly_what_the_script_renders():
    assert {name: committed(name) for name in compose.rendered()} == compose.rendered()


def test_the_script_writes_every_config(tmp_path, monkeypatch):
    monkeypatch.setattr(sys, "argv", ["compose_config.py", "--out", str(tmp_path)])
    with pytest.raises(SystemExit) as exited:
        runpy.run_path(str(compose.ROOT / "scripts" / "compose_config.py"), run_name="__main__")
    assert exited.value.code == 0
    assert {p.relative_to(tmp_path).as_posix(): p.read_text() for p in tmp_path.rglob("*") if p.is_file()} == compose.rendered()


def test_each_generated_file_names_its_generator():
    for name in ("nats/hub.conf", "nats/edge.conf"):
        assert committed(name).startswith("# GENERATED by scripts/compose_config.py")


@pytest.fixture
def harness_configs():
    cluster = Cluster()
    cluster.write_nats_configs()
    yield {"nats/hub.conf": (cluster.dir / "hub" / "nats.conf").read_text(),
           "nats/edge.conf": (cluster.dir / "edge-alpha" / "nats.conf").read_text()}
    shutil.rmtree(cluster.dir, ignore_errors=True)


@pytest.mark.enable_socket  # Cluster allocates loopback ports only; no network access
def test_compose_and_harness_nats_configs_differ_only_in_addresses(harness_configs):
    for name, harness_text in harness_configs.items():
        diff = difflib.ndiff(harness_text.splitlines(), body(committed(name)).splitlines())
        changed = [line[2:] for line in diff if line.startswith(("- ", "+ "))]
        assert changed, f"{name}: expected the addresses to differ"
        assert all(ADDRESS_LINE.match(line) for line in changed), f"{name}: {changed}"


def test_the_edge_config_carries_the_leaf_permissions_and_ddil_fixes():
    edge = committed("nats/edge.conf")
    assert 'deny_exports: ["unit.>", "passes.>", "node.>"]' in edge
    assert 'deny_imports: ["node.>"]' in edge
    assert 'first_info_timeout: "20s"' in edge
    assert 'ping_interval: "5s"' in edge and "ping_max: 3" in edge


def test_the_hub_config_carries_its_ddil_fixes():
    hub = committed("nats/hub.conf")
    assert "no_advertise: true" in hub
    assert re.search(r"authorization \{\s+timeout: 30\s+\}", hub)
    assert 'ping_interval: "5s"' in hub and "ping_max: 3" in hub


def test_each_bus_listens_on_its_own_loopback_and_only_the_leaf_listener_is_open():
    hub, edge = committed("nats/hub.conf"), committed("nats/edge.conf")
    for conf in (hub, edge):
        assert f'listen: "127.0.0.1:{compose.NATS_CLIENT_PORT}"' in conf
        assert f'http: "127.0.0.1:{compose.NATS_MONITOR_PORT}"' in conf
    assert f'listen: "0.0.0.0:{compose.HUB_LEAF_PORT}"' in hub


def test_the_edge_leaf_dials_toxiproxy_and_toxiproxy_forwards_to_the_hub_leaf_listener():
    edge = committed("nats/edge.conf")
    assert f'url: "nats-leaf://toxiproxy:{compose.LINK_PORT}"' in edge
    assert json.loads(committed("toxiproxy.json")) == [{
        "name": "leaf",
        "listen": f"0.0.0.0:{compose.LINK_PORT}",
        "upstream": f"hub-nats:{compose.HUB_LEAF_PORT}",
        "enabled": True,
    }]
