"""Tier 3 - validation against NASA CARA's published cases.

Three independent kinds of evidence, all from files NASA published
(fixtures/cara/, vendored unmodified, integrity-checked below):

1. **Pc2D values.** 53 real operational conjunctions (CARA's
   PcTestCaseCDMs set: HST, TERRA, SWIFT, ...), the 11 Alfano (2009)
   benchmark cases read from their CDM encodings, and CARA's Omitron unit
   test cases. Sentinel must reproduce CARA's number when configured the
   way CARA's reference computation is configured.

2. **Default-config outcomes.** The same inputs under Sentinel's default
   applicability gate. Alfano cases are low-velocity by design and must be
   refused; a non-positive-definite covariance must be refused, not
   repaired (a documented divergence from CARA).

3. **The gate against CARA's own verdicts.** CARA flags 29 of the 53
   operational events as outside the 2D method's validity. Sentinel's
   gate must refuse every one of them - a 2D Pc that CARA considers wrong
   must never be returned. False positives (refusing where CARA would
   compute) are counted and bounded; the threshold was calibrated on this
   set, which docs/validation-report.md states next to the result.

Expected values are transcribed from NASA's files by
scripts/transcribe_cara_fixtures.py, never generated by Sentinel.
"""

import math

import numpy as np
import pytest

from sentinel.risk.encounter import build_encounter_plane
from sentinel.risk.engine import assess
from sentinel.risk.integrate import gaussian_mass_over_disk
from sentinel.risk.types import Method
from sentinel.validation.cara import load_cases, verify_vendored_files

pytestmark = pytest.mark.tier3

CASES = load_cases()
BY_ID = {c.case_id: c for c in CASES}
PC2D_CASES = [c for c in CASES if "pc2d" in c.expected]
OUTCOME_CASES = [c for c in CASES if "default_outcome" in c.expected]
OPERATIONAL = [c for c in CASES if c.group == "cara_operational"]

# In-sample false positives at the calibrated threshold (see module docstring).
MAX_GATE_FALSE_POSITIVES = 5


def test_fixture_file_is_present_and_complete():
    assert len(OPERATIONAL) == 53, "CARA's operational set has 53 conjunctions"
    assert len([c for c in CASES if c.group == "alfano_2009"]) == 11
    assert sum(c.expected["cara_pc2d_usage_violation"] for c in OPERATIONAL) == 29


def test_vendored_nasa_files_are_unmodified():
    assert verify_vendored_files() == []


def test_every_case_documents_provenance_and_tolerance():
    """A case without provenance is not evidence of anything."""
    for case in CASES:
        prov = case.raw["provenance"]
        assert prov.get("source_path") and prov.get("source_lines"), case.case_id
        assert case.raw["tolerance"].get("justification"), case.case_id
        if case.raw.get("config_override"):
            assert case.raw.get("override_justification"), case.case_id


def test_fixture_inputs_are_the_vendored_bytes():
    import hashlib

    from sentinel.validation.cara import CARA_DIR

    for case in CASES:
        inputs = case.raw["inputs"]
        if "cdm_file" in inputs:
            digest = hashlib.sha256((CARA_DIR / inputs["cdm_file"]).read_bytes()).hexdigest()
            assert digest == inputs["sha256"], case.case_id


# --- 1. Pc2D values --------------------------------------------------------
@pytest.mark.parametrize("case", PC2D_CASES, ids=[c.case_id for c in PC2D_CASES])
def test_pc2d_matches_published_cara_value(case):
    result = assess(case.conjunction(), case.override_config())

    assert result.method is Method.FOSTER_ESTES_2D, result.refusal_reason
    expected = case.expected["pc2d"]
    assert np.isclose(result.pc, expected, rtol=case.rtol, atol=0.0), (
        f"{case.case_id}: Sentinel {result.pc!r} vs CARA {expected!r} "
        f"(rel {abs(result.pc - expected) / expected:.2e}, rtol {case.rtol})"
    )


def test_miss_distance_convention_explains_omitron_case_2():
    """CARA's unadjusted methods take |r| - including the component along
    the relative velocity - as the in-plane miss distance. Sentinel uses the
    in-plane miss at the refined TCA. Adopting CARA's convention on the same
    encounter plane must reproduce CARA's published value; Sentinel's own
    value must differ from it by exactly that effect and no more."""
    case = BY_ID["OMITRON-02-INLINE"]
    conj = case.conjunction()
    plane = build_encounter_plane(conj, case.raw["hbr_m"], refine_tca=False)

    full_r = np.linalg.norm(
        (conj.secondary.position_km - conj.primary.position_km) * 1000.0
    )
    cara_convention = gaussian_mass_over_disk(plane.cov_2d_m2, np.array([full_r, 0.0]), plane.hbr_m)
    expected = case.expected["pc2d_full_r_convention"]
    assert np.isclose(cara_convention, expected, rtol=case.rtol, atol=0.0)

    sentinel = assess(conj).pc
    assert not np.isclose(sentinel, expected, rtol=1e-6)
    assert np.isclose(sentinel, expected, rtol=1e-3)


# --- 2. default-config outcomes --------------------------------------------
@pytest.mark.parametrize("case", OUTCOME_CASES, ids=[c.case_id for c in OUTCOME_CASES])
def test_default_configuration_outcome(case):
    result = assess(case.conjunction())
    want = case.expected["default_outcome"]
    if want == "PC":
        assert result.method is Method.FOSTER_ESTES_2D, result.refusal_reason
    else:
        _, reason = want.split(":")
        assert result.method is Method.REFUSED
        assert result.refusal_reason.value == reason
        assert result.pc is None


# --- 3. the gate against CARA's own usage-violation verdicts ---------------
def _gate_confusion():
    tp, fn, fp, tn = [], [], [], []
    for case in OPERATIONAL:
        refused = assess(case.conjunction()).method is Method.REFUSED
        flagged = case.expected["cara_pc2d_usage_violation"]
        {(True, True): tp, (False, True): fn, (True, False): fp, (False, False): tn}[
            (refused, flagged)
        ].append(case.case_id)
    return tp, fn, fp, tn


def test_gate_refuses_every_event_cara_says_2d_cannot_handle():
    """The dangerous direction: returning a 2D Pc CARA considers invalid.
    Some of these events have 3D Nc up to 60,000x the 2D value."""
    tp, fn, _, _ = _gate_confusion()
    assert fn == [], f"gate returned a Pc for CARA-flagged events: {fn}"
    assert len(tp) == 29


def test_gate_false_positives_stay_bounded():
    _, _, fp, tn = _gate_confusion()
    assert len(fp) <= MAX_GATE_FALSE_POSITIVES, fp
    assert len(fp) + len(tn) == 24


def test_accepted_events_agree_with_3d_where_cara_says_2d_is_valid():
    """Where both CARA and Sentinel accept the 2D method, CARA's 3D Nc
    should confirm it. This checks the premise of the gate, not the gate."""
    for case in OPERATIONAL:
        result = assess(case.conjunction())
        if result.method is Method.FOSTER_ESTES_2D:
            nc3d = case.expected["nc3d"]
            assert math.isclose(result.pc, nc3d, rel_tol=0.05), (
                f"{case.case_id}: accepted 2D Pc {result.pc:.3e} vs CARA Nc3D {nc3d:.3e}"
            )
