"""The Compose stack (deploy/compose/compose.yaml) as the harness sees it.

    [edge] -- nats(edge) --leaf--> toxiproxy --> nats(hub) -- [hub]

The same topology as cluster.py, in containers. Each node is two containers
sharing one network namespace, like a pod, so the templates' loopback
listeners keep their meaning: a node's bus is reachable by that node only.
Toxiproxy is the one container on both the hub's and the edge's network.

`rendered()` is every config the stack mounts, made by the functions the
process harness uses; only the addresses differ. scripts/compose_config.py
writes them and tests/test_compose_config.py holds them to that.
"""

from __future__ import annotations

import json
import pathlib

from .cluster import ROOT, edge_nats_conf, hub_nats_conf, leaf_proxy

COMPOSE_DIR = ROOT / "deploy" / "compose"
COMPOSE_FILE = COMPOSE_DIR / "compose.yaml"

NATS_CLIENT_PORT = 4222   # each node's own bus, on its namespace's loopback
NATS_MONITOR_PORT = 8222
HUB_LEAF_PORT = 7422      # the hub's leaf listener, on the hub's network only
LINK_PORT = 17422         # Toxiproxy's end of the leaf link, where the edge dials
HUB_CONSOLE = "http://127.0.0.1:8000"   # published on the host's loopback
EDGE_CONSOLE = "http://127.0.0.1:8001"


def _generated(template: str) -> str:
    return f"# GENERATED by scripts/compose_config.py from deploy/nats/{template}; edit that, then `make compose-config`.\n"


def rendered() -> dict[str, str]:
    """Path under deploy/compose -> content."""
    return {
        "nats/hub.conf": _generated("hub.conf.tmpl")
        + hub_nats_conf(NATS_CLIENT_PORT, NATS_MONITOR_PORT, f"0.0.0.0:{HUB_LEAF_PORT}"),
        "nats/edge.conf": _generated("edge.conf.tmpl")
        + edge_nats_conf(NATS_CLIENT_PORT, NATS_MONITOR_PORT, f"nats-leaf://toxiproxy:{LINK_PORT}"),
        "toxiproxy.json": json.dumps([leaf_proxy(f"0.0.0.0:{LINK_PORT}", f"hub-nats:{HUB_LEAF_PORT}")], indent=2)
        + "\n",
    }


def write_configs(out: pathlib.Path = COMPOSE_DIR) -> list[pathlib.Path]:
    written = []
    for name, text in rendered().items():
        path = out / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        written.append(path)
    return written
