"""Render harness/results/*.json into docs/ddil-results.md (generated file).

    python -m harness.report [--if-complete]

The report is written from every scenario or not at all: with any result
missing it names the missing scenarios and writes nothing, so one scenario
run on a fresh clone cannot drop the other five from the committed report.
It exits 1 then, or 0 with --if-complete (for `make opsec`).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

from .scenarios import SCENARIOS

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "docs" / "ddil-results.md"
RESULTS = HERE / "results"
ORDER = list(SCENARIOS)


def missing() -> list[str]:
    """The scenarios with no result in RESULTS, in report order."""
    return [name for name in ORDER if not (RESULTS / f"{name}.json").exists()]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m harness.report", description=__doc__.split("\n\n")[0])
    parser.add_argument("--if-complete", action="store_true",
                        help="with a result missing, skip the report and exit 0 instead of 1")
    args = parser.parse_args(argv)
    absent = missing()
    if absent:
        print(f"not writing {OUT.name}: no result for {', '.join(absent)} in {RESULTS}. "
              "Run every scenario (make ddil) to regenerate it.", file=sys.stderr)
        return 0 if args.if_complete else 1
    OUT.write_text(render({name: json.loads((RESULTS / f"{name}.json").read_text()) for name in ORDER}))
    print(f"wrote {OUT}")
    return 0


def render(results: dict[str, dict]) -> str:
    lines = [
        "# DDIL test results",
        "",
        "Generated by `python -m harness.report` from `harness/results/`. Every number",
        "below was measured on a real two-node deployment: two nats-server processes",
        "joined by a leafnode connection, with Toxiproxy shaping that TCP link, and",
        "two Sentinel nodes (hub and edge) on top. Nothing is simulated in-process.",
        "",
        "| scenario | result | assertions | ran |",
        "|---|---|---|---|",
    ]
    for r in results.values():
        passed = sum(a["passed"] for a in r["assertions"])
        lines.append(
            f"| {r['scenario']} | {'PASS' if r['passed'] else '**FAIL**'} | {passed}/{len(r['assertions'])} | {r['ran_at'][:16]}Z |"
        )
    lines.append("")
    for name, r in results.items():
        lines += [f"## {r['scenario']}", ""]
        for note in r.get("notes", []):
            lines += [note, ""]
        for a in r["assertions"]:
            lines.append(f"- {'PASS' if a['passed'] else '**FAIL**'} - {a['name']}" + (f" ({a['detail']})" if a["detail"] else ""))
        lines.append("")
        if name == "limited":
            e, f = r["metrics"]["edf"], r["metrics"]["fifo"]
            lines += [
                "| measured over ~8 kbit/s + 600 ms | EDF (Sentinel) | FIFO (transport order) |",
                "|---|---|---|",
                f"| every event visible (summaries) | {e['times_s']['all_summaries']} s | {f['times_s']['all_summaries']} s |",
                f"| **most urgent event's full CDM** | **{e['times_s']['most_urgent_full']} s** | **{f['times_s']['most_urgent_full']} s** |",
                f"| every event verified | {e['times_s']['all_latest_verified']} s | {f['times_s']['all_latest_verified']} s |",
                f"| measured payload rate | {e['measured_rate_bytes_per_s']} B/s | {f['measured_rate_bytes_per_s']} B/s |",
                "",
                f"Same link, same {e['records']} records ({e['record_bytes']:,} bytes of KVN), only the order differs:",
                f"the most urgent full record arrives **{r['metrics']['most_urgent_speedup']}x sooner** with earliest-deadline-first.",
                "The payload rate exceeds the 1 kB/s link rate because NATS compresses the leafnode stream (s2).",
                "",
            ]
        else:
            metrics = {k: v for k, v in r["metrics"].items() if not isinstance(v, dict)}
            if metrics:
                lines += ["| metric | value |", "|---|---|"] + [f"| {k} | {v} |" for k, v in metrics.items()] + [""]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
