"""Render harness/results/*.json into docs/ddil-results.md (generated file).

    python -m harness.report [--if-complete]

The report is written from every scenario or not at all: with any result
missing it names the missing scenarios and writes nothing, so one scenario
run on a fresh clone cannot drop the other five from the committed report.
It exits 1 then, or 0 with --if-complete (for `make opsec`).
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

from .scenarios import SCENARIOS
from .stats import describe

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "docs" / "ddil-results.md"
RESULTS = HERE / "results"
ORDER = list(SCENARIOS)


def missing() -> list[str]:
    """The scenarios with no result in RESULTS, in report order."""
    return [name for name in ORDER if not (RESULTS / f"{name}.json").exists()]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m harness.report", description=__doc__.split("\n\n")[0])
    parser.add_argument("--if-complete", action="store_true",
                        help="with a result missing, skip the report and exit 0 instead of 1")
    args = parser.parse_args(argv)
    absent = missing()
    if absent:
        print(f"not writing {OUT.name}: no result for {', '.join(absent)} in {RESULTS}. "
              "Run every scenario (make ddil) to regenerate it.", file=sys.stderr)
        return 0 if args.if_complete else 1
    OUT.write_text(render({name: json.loads((RESULTS / f"{name}.json").read_text()) for name in ORDER}))
    print(f"wrote {OUT}")
    return 0


def render(results: dict[str, dict]) -> str:
    lines = [
        "# DDIL test results",
        "",
        "Generated by `python -m harness.report` from `harness/results/`. Every number",
        "below was measured on a real two-node deployment: two nats-server processes",
        "joined by a leafnode connection, with Toxiproxy shaping that TCP link, and",
        "two Sentinel nodes (hub and edge) on top. Nothing is simulated in-process.",
        "",
        "| scenario | result | assertions | load (1 min, start → end) | ran |",
        "|---|---|---|---|---|",
    ]
    for r in results.values():
        passed = sum(a["passed"] for a in r["assertions"])
        load = r["load_1min"]
        lines.append(
            f"| {r['scenario']} | {'PASS' if r['passed'] else '**FAIL**'} | {passed}/{len(r['assertions'])} "
            f"| {load['start']} → {load['end']} | {r['ran_at'][:16]}Z |"
        )
    lines.append("")
    for name, r in results.items():
        lines += [f"## {r['scenario']}", ""]
        for note in r.get("notes", []):
            lines += [note, ""]
        for a in r["assertions"]:
            lines.append(f"- {'PASS' if a['passed'] else '**FAIL**'} - {a['name']}" + (f" ({a['detail']})" if a["detail"] else ""))
        lines.append("")
        if name == "limited":
            lines += limited_section(r["metrics"])
        else:
            metrics = {k: v for k, v in r["metrics"].items() if not isinstance(v, dict)}
            if metrics:
                lines += ["| metric | value |", "|---|---|"] + [f"| {k} | {v} |" for k, v in metrics.items()] + [""]
    return "\n".join(lines) + "\n"


def limited_section(m: dict) -> list[str]:
    """LIMITED: medians and ranges over repeated runs, what every run moved, and every run."""
    e, f, first = m["edf"], m["fifo"], m["runs"][0]

    def row(label: str, key: str, unit: str = "s", digits: int = 1, bold: bool = False) -> str:
        mark = "**" if bold else ""
        return f"| {mark}{label}{mark} | {mark}{describe(e[key], unit, digits)}{mark} | {mark}{describe(f[key], unit, digits)}{mark} |"

    return [
        f"| over ~8 kbit/s + 600 ms: median (range) of {m['runs_per_mode']} runs per mode | EDF (Sentinel) | FIFO (transport order) |",
        "|---|---|---|",
        row("leaf connection up over the shaped link", "link_up_s"),
        row("every event visible (summaries)", "all_summaries"),
        row("most urgent event's full CDM", "most_urgent_full", bold=True),
        row("every event verified", "all_latest_verified"),
        row("every record delivered", "all_records"),
        row("edge's rate estimate at the end", "rate_estimate_bytes_per_s", "B/s", 0),
        "",
        f"Same link, same {first['records_fetched']} records ({first['cdms']} CDMs, {first['cdm_bytes']:,} bytes of KVN, "
        f"and {first['element_sets']} element sets; {first['record_bytes']:,} bytes in all), queued at the hub before",
        "the link came up; only the order differs. The most urgent full record arrives",
        f"**{m['most_urgent_speedup']}x sooner** with earliest-deadline-first (the ratio of the medians).",
        "Times run from the moment the leaf connection came up over the shaped link.",
        "",
        "The rate estimate is the edge's own measure (`sentinel/linkstate/monitor.py`): payload bytes over",
        "each round trip's duration, smoothed, for transfers of 2,000 bytes or more. It is not the link's",
        "capacity. It counts bytes before NATS compresses them (s2), and every round trip carries about",
        "1.2 s of latency, so it moves with record size and compressibility. The link itself is the",
        "Toxiproxy preset above, checked at link-up and at the end of every run.",
        "",
        "Every run, in the order run:",
        "",
        "| run | mode | load (1 min, start → end) | link up | summaries | most urgent | all verified | all records | rate estimate |",
        "|---|---|---|---|---|---|---|---|---|",
        *(_limited_run_row(number, run) for number, run in enumerate(m["runs"], start=1)),
        "",
    ]


def _limited_run_row(number: int, run: dict) -> str:
    t, load = run["times_s"], run["load_1min"]
    return (
        f"| {number} | {run['mode'].upper()} | {load['start']} → {load['end']} | {run['link_up_s']} s "
        f"| {t['all_summaries']} s | {t['most_urgent_full']} s | {t['all_latest_verified']} s | {t['all_records']} s "
        f"| {run['rate_estimate_bytes_per_s']:,} B/s |"
    )


if __name__ == "__main__":
    sys.exit(main())
