"""Render harness/results/*.json into docs/ddil-results.md (generated file)."""

from __future__ import annotations

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "docs" / "ddil-results.md"
ORDER = ["denied", "limited", "intermittent", "degraded", "recovery", "opsec"]


def main() -> None:
    results = {n: json.loads((HERE / "results" / f"{n}.json").read_text()) for n in ORDER if (HERE / "results" / f"{n}.json").exists()}
    lines = [
        "# DDIL test results",
        "",
        "Generated by `python -m harness.report` from `harness/results/`. Every number",
        "below was measured on a real two-node deployment: two nats-server processes",
        "joined by a leafnode connection, with Toxiproxy shaping that TCP link, and",
        "two Sentinel nodes (hub and edge) on top. Nothing is simulated in-process.",
        "",
        "| scenario | result | assertions | ran |",
        "|---|---|---|---|",
    ]
    for r in results.values():
        passed = sum(a["passed"] for a in r["assertions"])
        lines.append(
            f"| {r['scenario']} | {'PASS' if r['passed'] else '**FAIL**'} | {passed}/{len(r['assertions'])} | {r['ran_at'][:16]}Z |"
        )
    lines.append("")
    for name, r in results.items():
        lines += [f"## {r['scenario']}", ""]
        for note in r.get("notes", []):
            lines += [note, ""]
        for a in r["assertions"]:
            lines.append(f"- {'PASS' if a['passed'] else '**FAIL**'} - {a['name']}" + (f" ({a['detail']})" if a["detail"] else ""))
        lines.append("")
        if name == "limited":
            e, f = r["metrics"]["edf"], r["metrics"]["fifo"]
            lines += [
                "| measured over ~8 kbit/s + 600 ms | EDF (Sentinel) | FIFO (transport order) |",
                "|---|---|---|",
                f"| every event visible (summaries) | {e['times_s']['all_summaries']} s | {f['times_s']['all_summaries']} s |",
                f"| **most urgent event's full CDM** | **{e['times_s']['most_urgent_full']} s** | **{f['times_s']['most_urgent_full']} s** |",
                f"| every event verified | {e['times_s']['all_latest_verified']} s | {f['times_s']['all_latest_verified']} s |",
                f"| measured payload rate | {e['measured_rate_bytes_per_s']} B/s | {f['measured_rate_bytes_per_s']} B/s |",
                "",
                f"Same link, same {e['records']} records ({e['record_bytes']:,} bytes of KVN), only the order differs:",
                f"the most urgent full record arrives **{r['metrics']['most_urgent_speedup']}x sooner** with earliest-deadline-first.",
                "The payload rate exceeds the 1 kB/s link rate because NATS compresses the leafnode stream (s2).",
                "",
            ]
        else:
            metrics = {k: v for k, v in r["metrics"].items() if not isinstance(v, dict)}
            if metrics:
                lines += ["| metric | value |", "|---|---|"] + [f"| {k} | {v} |" for k, v in metrics.items()] + [""]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
