#!/usr/bin/env python3
"""Write fixtures/wayfinder/ASSUMED-ephemeris-worldview3.json and its checksum.

    uv run python scripts/make_assumed_wayfinder_fixture.py

This is NOT Wayfinder output. Sentinel has no access to the Wayfinder API
and does not know its schema. The file holds the public CelesTrak element
set for WORLDVIEW-3 (NORAD 40115, fixtures/omm/celestrak-resource-20260924.json),
propagated by SGP4 through Skyfield to Earth-fixed (ITRS) positions every
60 s over the exercise day (2026-09-24T06:00Z + 24 h, an hour either side),
written in the schema sentinel/adapters/wayfinder.py ASSUMES. It gives the
adapter's contract test a realistic payload to parse.

Deterministic and offline: bundled timescale, no network, no JPL ephemeris.
Positions are rounded to 1 mm. `created` is the element set's epoch, copied
as published, so the age the pass provider reports is the age of the orbit
knowledge, not of this file. tests/adapters/test_wayfinder.py re-derives
every position from the element set and checks the SHA-256.
"""

import datetime as dt
import hashlib
import json
import pathlib
import re

from skyfield.api import EarthSatellite, load

from sentinel.ephemeris.tabulate import tabulate

ROOT = pathlib.Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "fixtures" / "omm" / "celestrak-resource-20260924.json"
OUT_DIR = ROOT / "fixtures" / "wayfinder"
OUT = OUT_DIR / "ASSUMED-ephemeris-worldview3.json"
NORAD_ID = 40115
START = dt.datetime(2026, 9, 24, 5, 0, tzinfo=dt.UTC)
STOP = dt.datetime(2026, 9, 25, 7, 0, tzinfo=dt.UTC)
STEP_S = 60.0
NUMBER_ROW = re.compile(r"\[\s*(-?[\d.eE+-]+(?:,\s*-?[\d.eE+-]+)*)\s*\]")


def build() -> dict:
    record = next(r for r in json.loads(SNAPSHOT.read_text()) if r["NORAD_CAT_ID"] == NORAD_ID)
    ts = load.timescale(builtin=True)
    table = tabulate(EarthSatellite.from_omm(ts, record), ts, START, STOP, step_s=STEP_S)
    return {
        "_sentinel": {
            "schema": "ASSUMED",
            "data_class": "DERIVED",
            "note": (
                "Generated by Sentinel; not Wayfinder output. SGP4 (Skyfield) Earth-fixed "
                "positions of a public CelesTrak element set, in the schema "
                "sentinel/adapters/wayfinder.py assumes."
            ),
            "source": f"fixtures/omm/{SNAPSHOT.name}, NORAD {NORAD_ID}, element-set epoch {record['EPOCH']}",
            "generator": "scripts/make_assumed_wayfinder_fixture.py",
        },
        "object": {"norad_id": NORAD_ID, "name": record["OBJECT_NAME"]},
        "frame": "ITRF",
        "time_system": "UTC",
        "created": record["EPOCH"] + "Z",
        "epochs": [f"{epoch:%Y-%m-%dT%H:%M:%S}Z" for epoch in table.epochs],
        "positions_km": [[round(float(v), 6) for v in row] for row in table.positions_km],
    }


def render(body: dict) -> bytes:
    """Indented JSON with each [x, y, z] row on one line, so the file diffs readably."""
    text = json.dumps(body, indent=1)
    return (NUMBER_ROW.sub(lambda m: "[" + ", ".join(m[1].replace(",", " ").split()) + "]", text) + "\n").encode()


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    raw = render(build())
    OUT.write_bytes(raw)
    digest = hashlib.sha256(raw).hexdigest()
    (OUT_DIR / "SHA256SUMS").write_text(f"{digest}  {OUT.name}\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(raw)} bytes, sha256 {digest[:16]}")


if __name__ == "__main__":
    main()
