#!/usr/bin/env python3
"""Generate docs/validation-report.md from closed-form comparisons.

Every expectation here is an analytic result, not a value produced by this
code on a previous run.
"""

import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from sentinel.risk.integrate import gaussian_mass_over_disk, maximize_pc_over_scale

OUT = pathlib.Path(__file__).resolve().parent.parent / "docs" / "validation-report.md"

lines = []
w = lines.append

w("# Sentinel Risk Engine - Validation Report")
w("")
w("Generated by `scripts/validation_report.py`. Every expected value below is")
w("either a closed form derived independently of the implementation or a")
w("value NASA published. No expectation in this report was produced by")
w("running this code.")
w("")
w("Sections 1-4 compare against closed forms. Sections 5-8 compare against")
w("values NASA CARA published: 53 real operational conjunctions, the Alfano")
w("(2009) benchmark cases, and CARA's Omitron unit-test cases. Those files")
w("are vendored unmodified under `fixtures/cara/` with provenance and")
w("checksums; the expected values are transcribed from them by")
w("`scripts/transcribe_cara_fixtures.py`.")
w("")

w("## 1. Rayleigh closed form")
w("")
w("Isotropic covariance centred on the disk integrates to `1 - exp(-R^2 / 2 sigma^2)`.")
w("")
w("| sigma (m) | R (m) | engine | closed form | rel. error |")
w("|---|---|---|---|---|")
worst_1 = 0.0
for sigma, radius in [(50.0, 5.0), (10.0, 10.0), (200.0, 1.0), (1.0, 3.0), (400.0, 20.0)]:
    got = gaussian_mass_over_disk(np.eye(2) * sigma**2, np.zeros(2), radius)
    exp = 1.0 - np.exp(-(radius**2) / (2.0 * sigma**2))
    err = abs(got - exp) / exp
    worst_1 = max(worst_1, err)
    w(f"| {sigma:g} | {radius:g} | {got:.12e} | {exp:.12e} | {err:.2e} |")
w("")
w(f"Worst relative error: **{worst_1:.2e}**")
w("")

w("## 2. Optimal covariance scale")
w("")
w("In the small-HBR isotropic limit the Pc-maximising scale factor is")
w("`k* = (d^2 / 2) / sigma^2`.")
w("")
w("| d (m) | sigma (m) | HBR (m) | engine k* | closed form | rel. error |")
w("|---|---|---|---|---|---|")
worst_2 = 0.0
for d, sigma, hbr in [
    (1000.0, 400.0, 1.0),
    (1000.0, 100.0, 1.0),
    (500.0, 250.0, 0.5),
    (2000.0, 1500.0, 2.0),
    (300.0, 50.0, 0.2),
]:
    k_star, _, _ = maximize_pc_over_scale(np.eye(2) * sigma**2, np.array([d, 0.0]), hbr)
    exp = (d**2 / 2.0) / sigma**2
    err = abs(k_star - exp) / exp
    worst_2 = max(worst_2, err)
    w(f"| {d:g} | {sigma:g} | {hbr:g} | {k_star:.9f} | {exp:.9f} | {err:.2e} |")
w("")
w(f"Worst relative error: **{worst_2:.2e}**")
w("")

w("## 3. Maximum probability of collision")
w("")
w("In the same limit the maximum is `Pc_max = R^2 / (e d^2)`, independent of")
w("the covariance actually supplied.")
w("")
w("| d (m) | sigma (m) | HBR (m) | engine Pc_max | closed form | rel. error |")
w("|---|---|---|---|---|---|")
worst_3 = 0.0
for d, sigma, hbr in [
    (1000.0, 400.0, 1.0),
    (1000.0, 2000.0, 1.0),
    (500.0, 250.0, 0.5),
    (2000.0, 100.0, 2.0),
]:
    _, pc_max, _ = maximize_pc_over_scale(np.eye(2) * sigma**2, np.array([d, 0.0]), hbr)
    exp = hbr**2 / (np.e * d**2)
    err = abs(pc_max - exp) / exp
    worst_3 = max(worst_3, err)
    w(f"| {d:g} | {sigma:g} | {hbr:g} | {pc_max:.9e} | {exp:.9e} | {err:.2e} |")
w("")
w(f"Worst relative error: **{worst_3:.2e}**")
w("")
w("Note that `Pc_max` does not depend on the supplied sigma, which is the")
w("point of computing it: the worst case over covariance scaling is a")
w("property of the encounter geometry, not of the quality of the tracking.")
w("")

w("## 4. Independent numerical oracle")
w("")
w("`tests/test_tier2_integration.py` cross-checks the engine's quadrature")
w("against `scipy.integrate.dblquad` operating in Cartesian coordinates -")
w("a different algorithm over a different parameterisation. Agreement is")
w("asserted at `rtol=1e-8` across isotropic, strongly anisotropic, and")
w("rotated-covariance cases.")
w("")

# ---------------------------------------------------------------------------
# NASA CARA published cases
# ---------------------------------------------------------------------------
import math  # noqa: E402

from sentinel.risk.engine import assess  # noqa: E402
from sentinel.risk.types import Method  # noqa: E402
from sentinel.validation.cara import load_cases  # noqa: E402

cases = load_cases()
operational = [c for c in cases if c.group == "cara_operational"]


def rel(a, b):
    return abs(a - b) / abs(b)


w("## 5. NASA CARA: 53 real operational conjunctions")
w("")
w("CARA's `PcTestCaseCDMs` set: real events from CARA operations, each with")
w("CARA's 2D Pc, 3D Nc, and its verdict on whether the 2D method is valid.")
w("Every CDM goes through Sentinel's own parser (`sentinel.cdm`) and engine.")
w("The Pc comparison disables Sentinel's applicability gate, because CARA's")
w("spreadsheet reports Pc2D for every event; section 6 evaluates the gate.")
w("")
errs = []
rows_out = []
for c in operational:
    conj = c.conjunction()
    forced = assess(conj, c.override_config())
    default = assess(conj)
    e = rel(forced.pc, c.expected["pc2d"])
    errs.append(e)
    rows_out.append((c, forced, default, e))
errs_sorted = sorted(errs)
w("| events | worst rel. error | median rel. error | Pc range |")
w("|---|---|---|---|")
pcs = [c.expected["pc2d"] for c in operational]
w(
    f"| {len(operational)} | **{max(errs):.1e}** | {errs_sorted[len(errs)//2]:.1e} | "
    f"{min(pcs):.1e} to {max(pcs):.1e} |"
)
w("")
w("CARA's README reports cross-platform differences in its own MATLAB")
w("results at the 1e-8 level and below; agreement is at that level.")
w("")
w("| primary | secondary | Sentinel Pc (gate off) | CARA Pc2D | rel. error | CARA Nc3D | CARA: 2D valid? | Sentinel default |")
w("|---|---|---|---|---|---|---|---|")
for c, forced, default, e in rows_out:
    flagged = c.expected["cara_pc2d_usage_violation"]
    verdict = "Pc" if default.method is Method.FOSTER_ESTES_2D else f"refused: {default.refusal_reason.value}"
    w(
        f"| {c.expected['primary']} | {c.expected['secondary']} | {forced.pc:.6e} | "
        f"{c.expected['pc2d']:.6e} | {e:.1e} | {c.expected['nc3d']:.3e} | "
        f"{'no' if flagged else 'yes'} | {verdict} |"
    )
w("")

w("## 6. The applicability gate against CARA's own verdicts")
w("")
w("Sentinel refuses to return a 2D Pc when (a) relative speed is below")
w("100 m/s, or (b) the sagitta of either object's 1-sigma along-track arc,")
w("`sigma_T^2 / (2|r|)`, exceeds 0.1 of the smallest 1-sigma axis in the")
w("encounter plane. Along-track uncertainty lies along the curved orbit, not")
w("along its tangent; when that bend is comparable to the encounter plane's")
w("tightest dimension, a flat Gaussian no longer describes where the object")
w("can be.")
w("")
tp = fn = fp = tn = 0
fps = []
for c, _forced, default, _e in rows_out:
    refused = default.method is Method.REFUSED
    flagged = c.expected["cara_pc2d_usage_violation"]
    if refused and flagged:
        tp += 1
    elif flagged:
        fn += 1
    elif refused:
        fp += 1
        fps.append((c, default))
    else:
        tn += 1
w("| | CARA: 2D invalid | CARA: 2D valid |")
w("|---|---|---|")
w(f"| **Sentinel refuses** | {tp} | {fp} |")
w(f"| **Sentinel returns Pc** | **{fn}** | {tn} |")
w("")
w("The dangerous cell is the bottom-left one: a 2D Pc returned for an event")
w(f"CARA says 2D cannot handle. It is **{fn}**.")
w("")
fast = [
    (c.expected["nc3d"] / c.expected["pc2d"], d)
    for c, _, d, _ in rows_out
    if c.expected["cara_pc2d_usage_violation"] and d.relative_speed_m_s >= 100.0
]
slow_orders = [
    math.log10(c.expected["nc3d"] / c.expected["pc2d"])
    for c, _, d, _ in rows_out
    if c.expected["cara_pc2d_usage_violation"] and d.relative_speed_m_s < 100.0
]
lo = min(r for r, _ in fast)
hi = max(r for r, _ in fast)
w(f"What those refusals prevent: on the {len(fast)} flagged events above 100 m/s,")
w("which only the curvature test catches, CARA's 3D Nc differs from the 2D Pc")
w(f"by factors of {lo:.2g}x to {hi:,.0f}x - in both directions. On the")
w(f"{len(slow_orders)} slow events, the 2D Pc understates the 3D Nc by")
w(f"{min(slow_orders):.0f} to {max(slow_orders):.0f} orders of magnitude.")
w("")
w(f"The {fp} false positives are refusals where CARA would have computed; each")
w("is conservative (Sentinel withholds a number, it never states a wrong one):")
w("")
w("| primary | secondary | curvilinear ratio | CARA Pc2D | CARA Nc3D |")
w("|---|---|---|---|---|")
for c, d in fps:
    w(
        f"| {c.expected['primary']} | {c.expected['secondary']} | "
        f"{d.diagnostics.get('curvilinear_ratio', float('nan')):.2f} | "
        f"{c.expected['pc2d']:.3e} | {c.expected['nc3d']:.3e} |"
    )
w("")
w("**Calibration disclosure.** The 0.1 threshold was chosen on this same set of")
w("53 events, so the table above is in-sample agreement, not a held-out test.")
w("The nearest CARA-flagged event sits at a ratio of 0.17 (1.7x margin). The")
w("metric is a screening heuristic motivated by orbit geometry, not CARA's")
w("usage-violation algorithm, which propagates equinoctial covariances along")
w("curvilinear trajectories. Porting that algorithm, and the 3D Nc method it")
w("hands off to, is the documented next step (risk-engine-design.md s8).")
w("")

w("## 7. Alfano (2009) benchmark cases, read from CDM files")
w("")
w("CARA's unit test reads these inputs from spreadsheets; Sentinel reads the")
w("CDM encodings of the same cases with its own parser - two independent")
w("routes to the same number. All eleven are low-relative-velocity encounters")
w("(0.001 to 16 m/s); Sentinel's default gate refuses every one, which the")
w("3D column justifies.")
w("")
w("| case | HBR (m) | Sentinel Pc (gate off) | CARA Pc2D | rel. error | CARA Nc3D | Sentinel default |")
w("|---|---|---|---|---|---|---|")
for c in [c for c in cases if c.group == "alfano_2009"]:
    conj = c.conjunction()
    forced = assess(conj, c.override_config())
    default = assess(conj)
    w(
        f"| {c.case_id} | {c.raw['hbr_m']} | {forced.pc:.6e} | {c.expected['pc2d']:.6e} | "
        f"{rel(forced.pc, c.expected['pc2d']):.1e} | {c.expected['nc3d']:.4e} | "
        f"refused: {default.refusal_reason.value} |"
    )
w("")
w("CARA's own tolerance for this test is 1e-3 relative.")
w("")

w("## 8. Omitron cases and two documented divergences")
w("")
by_id = {c.case_id: c for c in cases}
c1 = by_id["OMITRON-01-INLINE"]
r1 = assess(c1.conjunction())
w(f"- **Omitron Case 1** (CARA `PcCircle`, high-accuracy mode): Sentinel "
  f"{r1.pc:.12e} vs CARA {c1.expected['pc2d']:.12e}, relative error "
  f"{rel(r1.pc, c1.expected['pc2d']):.1e}.")
c2 = by_id["OMITRON-02-INLINE"]
r2 = assess(c2.conjunction())
w(f"- **Omitron Case 2**: Sentinel {r2.pc:.10e} vs CARA "
  f"{c2.expected['pc2d_full_r_convention']:.10e} ({rel(r2.pc, c2.expected['pc2d_full_r_convention']):.1e}). "
  "The difference is fully explained by convention: CARA's unadjusted methods use |r|, "
  "including a 0.47 m component along the relative velocity, as the in-plane miss "
  "distance. Evaluating Sentinel's encounter plane with CARA's convention reproduces "
  "CARA's value to 1e-14 (asserted in Tier 3). Sentinel's convention matches CARA's "
  "TCA-adjusted Pc2D (section 5).")
c7 = by_id["OMITRON-07-NONPD"]
r7 = assess(c7.conjunction())
w(f"- **Omitron Test07, non-positive-definite covariance**: CARA repairs the "
  f"covariance and reports Pc = 0. Sentinel returns `{r7.method.value}` / "
  f"`{r7.refusal_reason.value}`. A repaired covariance is not the one the originator "
  "supplied, and a Pc of zero is a strong claim to make on its behalf.")
c8 = by_id["OMITRON-08-3DNC"]
r8f = assess(c8.conjunction(), c8.override_config())
r8 = assess(c8.conjunction())
w(f"- **Omitron Test08, 2D/3D disagreement**: forced 2D Pc {r8f.pc:.4e} "
  f"(CARA {c8.expected['pc2d']:.4e}, rel. error {rel(r8f.pc, c8.expected['pc2d']):.1e}); "
  f"CARA's 3D Nc is {c8.expected['nc3d']:.4e}, about 15 orders of magnitude higher. "
  f"Sentinel's default: `{r8.refusal_reason.value}`.")
w("")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
print(f"worst errors: rayleigh={worst_1:.2e} k_star={worst_2:.2e} pc_max={worst_3:.2e}")
