#!/usr/bin/env python3
"""Generate docs/validation-report.md from closed-form comparisons.

Every expectation here is an analytic result, not a value produced by this
code on a previous run.
"""

import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from sentinel.risk.integrate import gaussian_mass_over_disk, maximize_pc_over_scale

OUT = pathlib.Path(__file__).resolve().parent.parent / "docs" / "validation-report.md"

lines = []
w = lines.append

w("# Sentinel Risk Engine - Validation Report")
w("")
w("Generated by `scripts/validation_report.py`. Every expected value below is")
w("a closed form derived independently of the implementation. No expectation")
w("in this report was produced by running this code.")
w("")
w("NASA CARA published-case validation (Tier 3) is **not yet performed** -")
w("see `tests/test_tier3_cara_validation.py`. Those tests are skipped and the")
w("skip is reported in the suite output rather than suppressed.")
w("")

w("## 1. Rayleigh closed form")
w("")
w("Isotropic covariance centred on the disk integrates to `1 - exp(-R^2 / 2 sigma^2)`.")
w("")
w("| sigma (m) | R (m) | engine | closed form | rel. error |")
w("|---|---|---|---|---|")
worst_1 = 0.0
for sigma, radius in [(50.0, 5.0), (10.0, 10.0), (200.0, 1.0), (1.0, 3.0), (400.0, 20.0)]:
    got = gaussian_mass_over_disk(np.eye(2) * sigma**2, np.zeros(2), radius)
    exp = 1.0 - np.exp(-(radius**2) / (2.0 * sigma**2))
    err = abs(got - exp) / exp
    worst_1 = max(worst_1, err)
    w(f"| {sigma:g} | {radius:g} | {got:.12e} | {exp:.12e} | {err:.2e} |")
w("")
w(f"Worst relative error: **{worst_1:.2e}**")
w("")

w("## 2. Optimal covariance scale")
w("")
w("In the small-HBR isotropic limit the Pc-maximising scale factor is")
w("`k* = (d^2 / 2) / sigma^2`.")
w("")
w("| d (m) | sigma (m) | HBR (m) | engine k* | closed form | rel. error |")
w("|---|---|---|---|---|---|")
worst_2 = 0.0
for d, sigma, hbr in [
    (1000.0, 400.0, 1.0),
    (1000.0, 100.0, 1.0),
    (500.0, 250.0, 0.5),
    (2000.0, 1500.0, 2.0),
    (300.0, 50.0, 0.2),
]:
    k_star, _, _ = maximize_pc_over_scale(np.eye(2) * sigma**2, np.array([d, 0.0]), hbr)
    exp = (d**2 / 2.0) / sigma**2
    err = abs(k_star - exp) / exp
    worst_2 = max(worst_2, err)
    w(f"| {d:g} | {sigma:g} | {hbr:g} | {k_star:.9f} | {exp:.9f} | {err:.2e} |")
w("")
w(f"Worst relative error: **{worst_2:.2e}**")
w("")

w("## 3. Maximum probability of collision")
w("")
w("In the same limit the maximum is `Pc_max = R^2 / (e d^2)`, independent of")
w("the covariance actually supplied.")
w("")
w("| d (m) | sigma (m) | HBR (m) | engine Pc_max | closed form | rel. error |")
w("|---|---|---|---|---|---|")
worst_3 = 0.0
for d, sigma, hbr in [
    (1000.0, 400.0, 1.0),
    (1000.0, 2000.0, 1.0),
    (500.0, 250.0, 0.5),
    (2000.0, 100.0, 2.0),
]:
    _, pc_max, _ = maximize_pc_over_scale(np.eye(2) * sigma**2, np.array([d, 0.0]), hbr)
    exp = hbr**2 / (np.e * d**2)
    err = abs(pc_max - exp) / exp
    worst_3 = max(worst_3, err)
    w(f"| {d:g} | {sigma:g} | {hbr:g} | {pc_max:.9e} | {exp:.9e} | {err:.2e} |")
w("")
w(f"Worst relative error: **{worst_3:.2e}**")
w("")
w("Note that `Pc_max` does not depend on the supplied sigma, which is the")
w("point of computing it: the worst case over covariance scaling is a")
w("property of the encounter geometry, not of the quality of the tracking.")
w("")

w("## 4. Independent numerical oracle")
w("")
w("`tests/test_tier2_integration.py` cross-checks the engine's quadrature")
w("against `scipy.integrate.dblquad` operating in Cartesian coordinates -")
w("a different algorithm over a different parameterisation. Agreement is")
w("asserted at `rtol=1e-8` across isotropic, strongly anisotropic, and")
w("rotated-covariance cases.")
w("")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
print(f"worst errors: rayleigh={worst_1:.2e} k_star={worst_2:.2e} pc_max={worst_3:.2e}")
